//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace barffood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int idfood { get; set; }
        public string idanimal { get; set; }
        public string idrace { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> data_validade { get; set; }
        public Nullable<int> time_remain { get; set; }
        public string foto { get; set; }
        public string url { get; set; }
    
        public virtual animal animal { get; set; }
        public virtual Race Race { get; set; }
    }
}
